spring:
  profiles:
    active: localhost # 기본 환경 선택


  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: adjustmentScheduler
          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            misfireThreshold: 5000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

kafka:
  topic:
    group-id: zoo-adjustment
    hub-transactions:
      name: zoo.queueing.event.adjustment.updated.hub-transactions
      producer:
        acks: 1

    distributor-transactions:
      name: zoo.queueing.event.adjustment.updated.distributor-transactions
      producer:
        acks: 1

    store-transactions:
      name: zoo.queueing.event.adjustment.updated.store-transactions
      producer:
        acks: 1